// SPDX-License-Identifier: Apache-2.0

export const HTLC_ABI = [
  {
    type: "function",
    name: "claim",
    inputs: [
      { name: "contractId", type: "bytes32", internalType: "bytes32" },
      { name: "secret", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "escrows",
    inputs: [{ name: "contractId", type: "bytes32", internalType: "bytes32" }],
    outputs: [
      { name: "contractId", type: "bytes32", internalType: "bytes32" },
      { name: "payer", type: "address", internalType: "address payable" },
      { name: "payee", type: "address", internalType: "address payable" },
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "hashlock", type: "bytes32", internalType: "bytes32" },
      { name: "refundTimestamp", type: "uint64", internalType: "uint64" },
      { name: "status", type: "uint8", internalType: "enum Htlc.EscrowStatus" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEscrow",
    inputs: [{ name: "contractId", type: "bytes32", internalType: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct Htlc.Escrow",
        components: [
          { name: "contractId", type: "bytes32", internalType: "bytes32" },
          { name: "payer", type: "address", internalType: "address payable" },
          { name: "payee", type: "address", internalType: "address payable" },
          { name: "token", type: "address", internalType: "address" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "hashlock", type: "bytes32", internalType: "bytes32" },
          { name: "refundTimestamp", type: "uint64", internalType: "uint64" },
          { name: "status", type: "uint8", internalType: "enum Htlc.EscrowStatus" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lock",
    inputs: [
      { name: "contractId", type: "bytes32", internalType: "bytes32" },
      { name: "payee", type: "address", internalType: "address payable" },
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "hashlock", type: "bytes32", internalType: "bytes32" },
      { name: "refundTimestamp", type: "uint64", internalType: "uint64" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "refund",
    inputs: [{ name: "contractId", type: "bytes32", internalType: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "Claimed",
    inputs: [
      { name: "contractId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "secret", type: "bytes32", indexed: false, internalType: "bytes32" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Locked",
    inputs: [
      { name: "contractId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "payer", type: "address", indexed: true, internalType: "address" },
      { name: "payee", type: "address", indexed: true, internalType: "address" },
      { name: "token", type: "address", indexed: false, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "hashlock", type: "bytes32", indexed: false, internalType: "bytes32" },
      { name: "refundTimestamp", type: "uint64", indexed: false, internalType: "uint64" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Refunded",
    inputs: [{ name: "contractId", type: "bytes32", indexed: true, internalType: "bytes32" }],
    anonymous: false,
  },
  { type: "error", name: "AlreadyExists", inputs: [] },
  { type: "error", name: "ClaimTooLate", inputs: [] },
  { type: "error", name: "InvalidAmount", inputs: [] },
  { type: "error", name: "InvalidPayee", inputs: [] },
  { type: "error", name: "InvalidSecret", inputs: [] },
  { type: "error", name: "NotLocked", inputs: [] },
  { type: "error", name: "RefundTooEarly", inputs: [] },
  { type: "error", name: "RefundWindowOpen", inputs: [] },
  { type: "error", name: "TransferFailed", inputs: [] },
] as const;

export const ERC20_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_name", type: "string" },
      { name: "_symbol", type: "string" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "decimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "mint",
    inputs: [
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "name",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transfer",
    inputs: [
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferFrom",
    inputs: [
      { name: "from", type: "address" },
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "Approval",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "spender", type: "address", indexed: true },
      { name: "value", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { name: "from", type: "address", indexed: true },
      { name: "to", type: "address", indexed: true },
      { name: "value", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
] as const;
