// SPDX-License-Identifier: Apache-2.0

export { EvmHtlcRail } from "./rail.js";
export {
  EscrowStatus,
  type LockKind,
  type LockTerms,
  type SettlementRail,
  type OnChainEscrow,
  type EvmAddressResolver,
  type AssetResolver,
  type EvmHtlcRailConfig,
} from "./types.js";
export {
  StaticAddressResolver,
  Secp256k1KeyAddressResolver,
  CompositeAddressResolver,
} from "./resolver.js";
export {
  EvmRailError,
  UnsupportedLockKindError,
  InvalidTermsError,
  EscrowNotFoundError,
  EscrowNotLockedError,
  RefundWindowOpenError,
  ClaimTooLateError,
  RefundTooEarlyError,
  InvalidSecretError,
} from "./errors.js";
export {
  toEvmTimestamp,
  computeSha256,
  verifyPreimage,
  isValidHex32,
  normalizeHex32,
  areAddressesEqual,
} from "./utils.js";
export { HTLC_ABI, ERC20_ABI } from "./abi.js";
export {
  DealManager,
  DealStatus,
  DealError,
  InvalidDealTransitionError,
  DealValidationError,
  TCLK_DOMAIN,
  type ParticipantIdentity,
  type OfferFrame,
  type AcceptCore,
  type AcceptFrame,
  type LockFrame,
  type RevealFrame,
  type RefundFrame,
  type CancelFrame,
  type ReceiptFrame,
  type DealLedgerEvidence,
  type DealRecord,
  type CreateDealOfferParams,
  canonicalJson,
  toAscii,
  domainHash,
  computeOfferId,
  computeContractId,
  projectLockTerms,
} from "./deal.js";
export {
  TCLK_PREFIX,
  MAX_FRAME_CHARS,
  sweptText,
  TechnocoreSigner,
  TransportError,
  InvalidSignatureError,
  InvalidRoomError,
  MalformedFrameError,
  DealNotFoundError,
  isTclkLine,
  encodeTclkFrame,
  decodeTclkFrame,
  tryDecodeTclkFrame,
  type TclkFrame,
  type TechnocoreRecord,
  type TechnocoreTransport,
  InMemoryTechnocoreTransport,
  HttpTechnocoreTransport,
  type IngestResult,
  RoomDealAdapter,
} from "./transport.js";
export {
  type TcExportCommitment,
  type TcAuditStep,
  type TcInclusionProof,
  type ArchivedDealStageRecord,
  type DealArchive,
  type ArchiveOptions,
  type VerificationResult,
  DealArchivalError,
  computeLeafHash,
  computeNodeHash,
  verifyInclusionProofInMemory,
  sliceRawExportLines,
  verifyRecordSignature,
  createSignedExportRecord,
  TcLedgerCli,
  TcLedgerArchiver,
  verifyDealArchive,
} from "./archiver.js";
export {
  type SessionRole,
  type WalletSessionConfig,
  type SessionMetadata,
  type TokenBalanceInfo,
  type SessionBalance,
  type AppConfig,
  type ContactEntry,
  type ArchivedDealSummary,
  type ArchiveStoreIndex,
  SessionError,
  InsecureDemoAccountError,
  ArchiveStoreError,
  TamperedArchiveError,
  ArchiveNotFoundError,
  InvalidContactError,
  InsecureConfigError,
} from "./app/types.js";
export { WalletSession } from "./app/session.js";
export { ArchiveStore } from "./app/store.js";
export {
  DealWalletApp,
  type DealWalletAppConfig,
  type CreateOfferParams,
  type AcceptDealParams,
  OrchestratorError,
  UnknownTransactionOutcomeError,
  PreimageNotFoundError,
  DealStateMismatchError,
  UnauthorizedActorError,
} from "./app/orchestrator.js";
export {
  DealWalletServer,
  startDealWalletServer,
  toSafeDealDto,
  renderDashboardHtml,
  type DealWalletServerConfig,
  type SafeDealDto,
  type SafeSessionMetadataDto,
  type SafeBalanceDto,
  type SafeDealsResponseDto,
  type SafeArchivesResponseDto,
  type HealthResponseDto,
  type SafeMessageDto,
  type SafeMessagesResponseDto,
  type CreateOfferRequestDto,
  type DealActionResponseDto,
  type CliOptions,
} from "./app/server.js";
